name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: "🚀 Features"
    labels:
      - feature
      - enhancement
  - title: "🐛 Bug Fixes"
    labels:
      - bug
  - title: "🧰 Chores & Docs"
    labels:
      - docs
      - chore
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-template-commit: '- $SUMMARY ($SHORT_SHA)'
template: |
  ## What's changed

  $CHANGES

  ----
  _This release was drafted automatically._
