name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows-exe:
    runs-on: windows-latest
    outputs:
      artifact-path: ${{ steps.zip.outputs.zip-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: pwsh

      - name: Build EXE (packaging script)
        run: .\packaging\build_exe.ps1 -Entry "src\titansteelworks\gui.py" -DistName "TitanSteelworks.Chatbot" -OneFile $true
        shell: pwsh

      - name: Generate SHA256 checksum
        run: |
          Get-FileHash -Path .\dist\TitanSteelworks.Chatbot.exe -Algorithm SHA256 | ForEach-Object { $_.Hash } | Out-File -FilePath .\dist\TitanSteelworks.Chatbot.exe.sha256 -Encoding ascii
        shell: pwsh

      - name: Zip EXE + checksum
        id: zip
        run: |
          $zip = Join-Path -Path $PWD -ChildPath ("dist\TitanSteelworks.Chatbot.zip")
          if (Test-Path $zip) { Remove-Item $zip }
          Compress-Archive -Path .\dist\TitanSteelworks.Chatbot.exe, .\dist\TitanSteelworks.Chatbot.exe.sha256 -DestinationPath $zip
          Write-Output "::set-output name=zip-path::$zip"
        shell: pwsh

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automated Windows single-file EXE build for tag ${{ github.ref_name }}.
          draft: false
          prerelease: false

      - name: Upload release asset (zip)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/TitanSteelworks.Chatbot.zip
          asset_name: TitanSteelworks.Chatbot.zip
          asset_content_type: application/zip
